myapp:
  prod:
    to: Delsunil@example.com
    host: Delmail.example.com
    port: 2504535
    cc:
    - Delmike@example.com
    - david@example.com
    bcc:
    - Delsumit@example.com
    - Delvadmin@example.com
    credential:
      user-name: sunil1234
      password: xyz@1234

      app:
        dev:
          to: devsunil@example.com
          host: dev.example.com
          port: 250
          cc:
          - Delmike@example.com
          - david@example.com
          bcc:
          - Delsumit@example.com
          - Delvadmin@example.com
          credential:
            user-name: sunil1234
            password: xyz@1234